version: "3.9"
services:

  router:
    build: ../svcs/router-service
    restart: always
    ports:
      - "4000:4000"
      - "8088:8088"
    volumes:
      - ../svcs/router-service/src:/home/app/src

  mongodb:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_volume:/data/db
    command: mongod --quiet --logpath /dev/null

  build:
    build:
      dockerfile: dev.docker
    restart: always
    volumes:
      - ../:/home/node/app
    command: "yarn node build.mjs watch"

  build-tests:
    build:
      dockerfile: dev.docker
    restart: always
    volumes:
      - ../:/home/node/app
    command: "yarn node build.tests.mjs watch"

  etl-service:
    build: ../dist/etl-service
    init: true
    depends_on:
      - mongodb
      - build
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ../dist/etl-service/src:/home/node/app/src
    command: "nodemon src/index.mjs"

  ocm-service:
    build: ../dist/ocm-service
    init: true
    depends_on:
      - etl-service
      - build
    restart: always
    ports:
      - "4001:4000"
      - "8089:8088"
    volumes:
      - ../dist/ocm-service/src:/home/node/app/src
    command: "nodemon src/index.mjs"

  tests:
    build:
      context: ../dist/tests
    profiles:
      - donotstart
    init: true
    depends_on:
      - mongodb
      - build
      - build-tests
      - etl-service
    restart: always
    volumes:
      - ../dist/tests/src:/home/node/app/src
    command: "yarn node --test --watch src"

volumes:
  mongodb_volume:
