version: "3.9"
services:

  router:
    build: ../svcs/router-service
    restart: always
    ports:
      - "4000:4000"
      - "8088:8088"
    volumes:
      - ../svcs/router-service/src:/home/app/src

  mongodb:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_volume:/data/db
    command: mongod --quiet --logpath /dev/null

  etl-service:
    build:
      dockerfile: ../../svcs/etl-service/Dockerfile
      context: ../dist/etl-service
    init: true
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ../dist/etl-service/src:/home/node/app/src
      - ../.yarn:/home/node/.yarn
    command: "yarn nodemon src/index.mjs"

  ocm-service:
    build:
      dockerfile: ../../svcs/ocm-service/Dockerfile
      context: ../dist/ocm-service
    init: true
    depends_on:
      - etl-service
    restart: always
    ports:
      - "4001:4000"
      - "8089:8088"
    volumes:
      - ../dist/ocm-service/src:/home/node/app/src
      - ../.yarn:/home/node/.yarn
    command: "yarn nodemon src/index.mjs"

volumes:
  mongodb_volume:
